name: Build APK

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK 36
        run: |
          sdkmanager "platforms;android-36" "build-tools;36.0.0"

      - name: Accept licenses
        run: yes | sdkmanager --licenses

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up release keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > ./keystore.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      # 4️⃣ Set environment variables for signing
      - name: Set signing environment variables
        run: |
          echo "KEYSTORE_PATH=./keystore.jks" >> $GITHUB_ENV
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV
        
      - name: Build APK
        run: ./gradlew assembleRelease --stacktrace --info

      - name: List APK files
        run: |
          echo "Listing APK outputs directory:"
          ls -R app/build/outputs/apk || true

          echo ""
          echo "Finding all APK files:"
          find app/build/outputs -type f -name "*.apk" || true
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk
